ENG-1191
atlasapi/atlas pull request #1587
Opened 2022-05-13 09:25 UTC by IvanKaraslavov

Adds a new unpublishing mode which unpublishes not only the piece of content but its hierarchy. What the new mode is doing is:
1. Unpublish all children of the piece of content 
* if it is a brand then unpublish all its series and episodes
* if it is a series then unpublish all its episodes
3. Unpublish the parent if all its children are unpublished 
* if it is an episode and the series (or brand) doesn't have any other actively published children then unpublish the parent
* if it is a series and the brand doesn't have any other actively published children then unpublish the brand

2022-05-13 14:25 UTC, tristanbeardmore-gray requested changes

2022-05-13 14:25 UTC, tristanbeardmore-gray commented on src/main/java/org/atlasapi/system/PublishedStatusUpdater.java
> +                optionalUnpublishHierarchy.filter(Boolean::parseBoolean).isPresent();
```suggestion
        boolean unpublishHierarchy = Boolean.parseBoolean(req.getParameter(UNPUBLISH_HIERARCHY));
```

2022-05-13 14:25 UTC, tristanbeardmore-gray commented on src/main/java/org/atlasapi/system/PublishedStatusUpdater.java
> +
Add a check which throws an error if `unpublishHierarchy` is set to true when the mode is set to publish content.

2022-05-13 14:25 UTC, tristanbeardmore-gray commented on src/main/java/org/atlasapi/system/PublishedStatusUpdater.java
> +    private void unpublishHierarchy(LookupEntry lookupEntry, Described described) {
This method should call individual methods that handle each case to prevent this method becoming too large.

2022-05-13 14:25 UTC, tristanbeardmore-gray commented on src/main/java/org/atlasapi/system/PublishedStatusUpdater.java
> +                        unpublishBrandIfNecessary(lookupEntry, episode);
What about if there are series siblings that aren't unpublished? We seem to account for this in the other case but not here.

2022-05-13 14:25 UTC, tristanbeardmore-gray commented on src/main/java/org/atlasapi/system/PublishedStatusUpdater.java
> +                List<Identified> episodesFromBrand = mongoContentResolver.findChildrenForParent(series.getParent().getUri(), true).getAllResolvedResults();
What's different here compared to `unpublishBrandIfNecessary`? Do we need an `unpublishSeriesIfNecessary` too?

2022-05-13 14:25 UTC, tristanbeardmore-gray commented on src/main/java/org/atlasapi/system/UnpublishContentController.java
> +                new PublishedStatusUpdater(
Make the constructor accept a `PublishedStatusUpdater` instead of instantiating it here to reduce the number of constructor parameters needed.

2022-05-13 14:25 UTC, tristanbeardmore-gray commented on src/main/java/org/atlasapi/system/PublishedStatusUpdater.java
> +            // unpublish episodes
This is going to end up being horrendously slow if a large brand needs to be unpublished. This might not need changing now but this should be designed with a Kafka queue in mind that does the unpublishing in the background.

2022-05-17 09:46 UTC, tristanbeardmore-gray commented on src/main/java/org/atlasapi/system/PublishedStatusUpdater.java
> +                List<Identified> episodesFromBrand = mongoContentResolver.findChildrenForParent(series.getParent().getUri(), true).getAllResolvedResults();
Are you sure this is actually resolved?

2022-05-17 10:16 UTC, tristanbeardmore-gray requested changes

2022-05-17 10:16 UTC, tristanbeardmore-gray commented on src/main/java/org/atlasapi/system/PublishedStatusUpdater.java
> +        updateContent(false, lookupEntry, described);
I think this needs to be moved within the specific hierarchy unpublishing methods since it will interfere with the checks some of those do to check all children have been unpublished. It should happen after unpublishing any children of the subject content and before any attempts to unpublish the subject's parents.

2022-05-17 16:51 UTC, EmiEnache commented on src/main/java/org/atlasapi/system/PublishedStatusUpdater.java
> +        //TODO: Add Kafka queue that does the unpublishing in the background
Is this intentionally left behind, to be done another time?

2022-05-18 09:24 UTC, IvanKaraslavov commented on src/main/java/org/atlasapi/system/PublishedStatusUpdater.java
> +        //TODO: Add Kafka queue that does the unpublishing in the background
Yeah, it is intentional, for future improvement regarding unpublishing big brands with a lot of children

2022-05-18 09:45 UTC, merged