Improve merge on write
atlasapi/atlas pull request #1601
Opened 2022-11-30 19:08 UTC by EmiEnache

2022-12-07 18:36 UTC, EmiEnache commented on src/main/java/org/atlasapi/query/content/merge/VersionMerger.java
> +                if (sameLocation(getFirstLocation(existingEncoding), getFirstLocation(newEncoding))) {
Do you agree that this addresses the issue?
https://github.com/atlasapi/atlas/pull/1601/commits/41b2251466510db851afaeac35f3ba30c8b2d588

2022-12-08 10:39 UTC, tristanbeardmore-gray requested changes

2022-12-08 10:39 UTC, tristanbeardmore-gray commented on src/main/java/org/atlasapi/query/content/merge/FieldMergeStrategy.java
> +    public Set<MergeableFields> getFieldsToMerge() {
Can (and ideally should) be private in my opinion, doesn't appear to be used externally.

2022-12-08 10:39 UTC, tristanbeardmore-gray commented on src/main/java/org/atlasapi/query/content/merge/FieldMergeStrategy.java
> +    public void addFieldToMerge(MergeableFields field){
Realise this is pre-existing code but can we make this private whilst we're here? It's not used externally and would be a very quick and easy change to make this class effectively immutable.

2022-12-08 10:39 UTC, tristanbeardmore-gray commented on src/main/java/org/atlasapi/query/content/merge/FieldMergeStrategy.java
>      public static FieldMergeStrategy create() {
```suggestion
    public static FieldMergeStrategy none() {
```
If combined with the comment below about making `addFieldToMerge` we can then give this method a more meaningful name, which will improve the readability of the code for there places where we're intentionally doing no merging.

2022-12-08 10:39 UTC, tristanbeardmore-gray commented on src/main/java/org/atlasapi/query/content/merge/FieldMergeStrategy.java
> +    private static final Set<MergeableFields> DO_NOT_MERGE_BY_DEFAULT = ImmutableSet.of(
We should have a set of default fields rather than a set of non-default fields, the reason being that as we add new mergeable fields we'll constantly hit the same issue of not wanting to break existing behaviour. With a set of non-default fields this is a potential point of failure if someone forgets to update this set.

2022-12-08 10:39 UTC, tristanbeardmore-gray commented on src/main/java/org/atlasapi/query/content/merge/VersionMerger.java
> +    // this could maybe just be the .equals method of Location, but we don't have time to implement
Comment no longer applies

2022-12-08 10:40 UTC, tristanbeardmore-gray commented on src/main/java/org/atlasapi/query/content/merge/VersionMerger.java
> +                if (sameLocation(getFirstLocation(existingEncoding), getFirstLocation(newEncoding))) {
I think so, especially for a first implementation.

2022-12-08 12:05 UTC, tristanbeardmore-gray commented on src/main/java/org/atlasapi/query/content/merge/VersionMerger.java
> +            existing.setProvider(null);
This is technically different logic to before I believe. The old logic wouldn't change `existing`'s provider if `update`'s is null, whereas here we now change `existing` to be null.

2022-12-08 12:26 UTC, EmiEnache commented on src/main/java/org/atlasapi/query/content/merge/VersionMerger.java
> +            existing.setProvider(null);
I think this is the same as before. Old logic would actually change existing's provider if update's is null. I've reverted this to be exactly what it was before my attempted change.

2022-12-08 12:30 UTC, tristanbeardmore-gray commented on src/main/java/org/atlasapi/query/content/merge/VersionMerger.java
> +            existing.setProvider(null);
Yeah ignore me, the diff I was looking at was based off a different commit and not master I think

2022-12-08 12:30 UTC, tristanbeardmore-gray approved these changes

2022-12-12 18:56 UTC, merged